"""empty message

Revision ID: 3e5daad67541
Revises: d849744ed6e8
Create Date: 2018-07-18 16:47:27.474976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5daad67541'
down_revision = 'd849744ed6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('books', sa.String(length=13), nullable=True))
    op.drop_constraint('author_book_isbn_fkey', 'author', type_='foreignkey')
    op.create_foreign_key(None, 'author', 'book', ['books'], ['isbn'])
    op.drop_column('author', 'book_isbn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('book_isbn', sa.VARCHAR(length=13), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'author', type_='foreignkey')
    op.create_foreign_key('author_book_isbn_fkey', 'author', 'book', ['book_isbn'], ['isbn'])
    op.drop_column('author', 'books')
    # ### end Alembic commands ###
