"""empty message

Revision ID: a59e3f61f5fc
Revises: 3e5daad67541
Create Date: 2018-07-18 18:44:59.327927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59e3f61f5fc'
down_revision = '3e5daad67541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('book', 'nickname',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'nickname',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('author', 'name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
